apiVersion: v1
kind: Namespace
metadata:
  name: gonzalodevarona
  labels:
    name: gonzalodevarona

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: simple
  namespace: gonzalodevarona
spec:
  replicas: 6
  selector:
    app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: simple
        image: gonzalodevarona/simple
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            host:
            scheme: HTTP
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 60


---

apiVersion: v1
kind: Service
metadata:
  name: svc-simple
  namespace: gonzalodevarona
  labels:
    app: simple
spec:
  type: LoadBalancer
  selector:
    app: simple
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http

---

apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: gonzalodevarona
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu:latest
    command:
      - /bin/bash
      - -c
      - |
        apt-get -y update
        apt-get -y install curl
        sleep 3600
    readinessProbe:
      exec:
        command:
          - /bin/sh
          - -c
          - curl $SVC_SIMPLE_SERVICE_HOST:$SVC_SIMPLE_SERVICE_PORT
      initialDelaySeconds: 5
      periodSeconds: 60
    
